GL_INCLUDE = /usr/X11R6/include
GL_LIB = /usr/X11R6/lib

SOURCES = main.c cube/cube.c utils/utils.c shader/shader.c program/program.c

OBJECTS = $(SOURCES:.c=.o)
EXECUTABLE = ./start

build: $(OBJECTS)
	gcc -o $(EXECUTABLE) $^ -L$(GL_LIB) -lGL -lglut -lGLEW -lm

start: build
	$(EXECUTABLE)

.c.o:
	gcc -c -o $@ $< -I$(GL_INCLUDE)

clean:
	rm -f $(EXECUTABLE) $(OBJECTS)